apiVersion: v1
kind: Service
metadata:
  name: paas-node-exporter
  namespace: paas-monitoring
  labels:
    paas-node-exporter: "true"
    app: paas-node-exporter
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics
      protocol: TCP
  selector:
    paas-node-exporter: "true"
